version: '3.8'
services:
  nestcrud:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: ./.env
    command: npm run start:dev
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - DB_HOST=mysqldb
      - DB_NAME=$DB_NAME
      - DB_USER=$USER_NAME
      - DB_PASSWORD=$USER_PASSWORD
      - PORT=3001
    
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    depends_on:
      - mysqldb

  mysqldb:
  # line below for mac with m1/m2 chip
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $USER_NAME
      MYSQL_PASSWORD: $USER_PASSWORD
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  mysql_config:
